[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "b3-2d"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pyvista",
    "rich",
    "treeparse",
    "cgfoil",
    "statesman",
    "matplotlib",
    "numpy",
]

[project.scripts]
b3-2d = "b3_2d.cli:main"

# [tool.uv.sources]
# cgfoil = { workspace = true }
